// This file is auto-generated for icon name mapping reference
// Do not import in production

export const ionIconNames = [
  'information-circle-outline',
  'camera-outline',
  'notifications-outline',
  'information-circle',
  'stopwatch',
  'trophy',
  'person',
  'camera',
  'checkmark-circle',
  'images-outline',
  'notifications',
  'time-outline',
  'trophy-outline',
  'flash-outline',
  'chevron-back',
  'chevron-forward',
  'log-out-outline',
  'stats-chart-outline',
  'person-outline',
  'warning-outline',
  'trash-outline',
  'image-outline',
  'pencil',
  'arrow-forward-outline',
  'document-text-outline',
  'close',
  'time',
  'document-text',
  'image',
  'trash',
  'refresh',
  'alert-circle',
  'checkmark',
  'mail-outline',
  'lock-closed-outline',
  'play',
  'stop',
  'globe-outline',
  'medal-outline',
  'arrow-back-outline',
];
